language: node_js
node_js:
  - "13.8"
sudo: required
services:
  - docker
before_script:
  - npm install
script:
  # - npm test
  - docker build -t twilio-teneo-sms-conversational .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag twilio-teneo-sms-conversational $DOCKER_USER/twilio-teneo-sms-conversational:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/twilio-teneo-sms-conversational:$TRAVIS_BUILD_NUMBER
  - docker tag twilio-teneo-sms-conversational $DOCKER_USER/twilio-teneo-sms-conversational:latest
  - docker push $DOCKER_USER/twilio-teneo-sms-conversational:latest
