version: "3"
services:
  twilio-teneo-sms-conversational:
    image: jolzee/twilio-teneo-sms-conversational
    container_name: twilio-teneo-sms-conversational
    ports:
      - "3000:3000"
    env_file:
      - TIE_URL=https://<TIE-HOST>/<TIE-CTX-PATH>/
  ngrok:
    image: "wernight/ngrok:latest"
    container_name: ngrok
    command:
      [sh, -c, "echo NGROK Admin URL http://localhost:4040 && /entrypoint.sh"]
    links:
      - twilio-teneo-sms-conversational:http
    ports:
      - "4040:4040"
    environment:
      - NGROK_PORT=twilio-teneo-sms-conversational:3000
      - NGROK_REGION=us
      - NGROK_BINDTLS=true
